//
// Created by Nylander on 16-09-2021.
//

#ifndef MANDATORY_ASSIGNMENT_SHELL_STRING_H
#define MANDATORY_ASSIGNMENT_SHELL_STRING_H

#define MAX_STRING_LENGTH 32768

char* newString();

#endif //MANDATORY_ASSIGNMENT_SHELL_STRING_H
